### PR TITLE
Fixes #1 Broken links due to punctuation

### LINKED ISSUE #1: Broken links due to punctuation
Hi! Thank you for this amazing webapp, it's an indispensable tool for me.

I'm seeing some TOC items receive broken links. Consider this source markdown:

```md
# Hi, @dohliam!
```
Here's how GitHub renders it. Note the id:

```html
<h1 id="hi-dohliam">Hi, @dohliam!</h1>
```

Here's how this header should be targeted from a TOC:

```md
* [Hi, @dohliam!](#hi-dohliam)
```
Here's how tocdown renders it, producing a broken link:

```md
* [Hi, @dohliam!](#hi,-@dohliam!)
```

### PR DESCRIPTION
**Pull request by lolmaus**
I've tested it against [Deveo/ember-emojione](https://github.com/Deveo/ember-emojione) readme which I'm working on.

image

The circular icons on the right indicate valid links. My IDE tests each link to have a corresponding anchor.

### CODE REVIEW

**Comment by lolmaus** [comment]
I've deployed my fix to https://lolmaus.github.io/tocdown/ for you to try out.

**Comment by dohliam** [comment]
Hi @lolmaus, this looks great and even preserves the underscore in links the way Github does. Thanks! The only issue is that this breaks Unicode support (see my comments on issue #1 ). I've added a few tests to the `test.md` file to show how Github deals with various cases. If you have any ideas of how to fix this without breaking Unicode links I'd be happy to merge this.

**Comment by lolmaus** [comment]
I've pushed a fix that uses [this solution](http://stackoverflow.com/a/22075070/901944) that accounts for word characters in most languages, except for Hindi, Telugu and maybe some others.

We still don't know which of them GitHub passes through, so it's still unreliable. But in my opinion, it's the most reliable variant that we have.

https://lolmaus.github.io/tocdown/

image

**Comment by dohliam** [comment]
Fantastic! As far as I can tell this works perfectly (at least on the test file). There are a couple of conflicts since I've pushed to the repo in the meantime, but I'll try to resolve them and merge this later today. Thanks again!

**Comment by lolmaus** [comment]
I've resolved the merge conflict.

Note that the Ruby version requires a similar update.

**Comment by dohliam** [comment]
Perfect -- thanks for the quick response! I'll update the ruby version as well in a follow up commit.

**Comment by lolmaus** [comment]
image

**Pull request merged**
